name: reviewdog

on: [pull_request]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    name: runner / golangci-lint
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.github_token }}
          level: warning
          golangci_lint_flags: "--config=.github/.golangci.yml"
          go_version: '1.17'
